# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1

orbs:
  heroku: circleci/heroku@0.0.4

workflows:
  heroku_deploy:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
    executor: heroku/default
    steps:
      - heroku/install
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build --cache-from=app -t nodejs-ipfs-backend-template .

      - run:
          name: Push to Docker Hub
          command: |
            docker login --username=$HEROKU_LOGIN --password=$MY_HEROKU_API_KEY registry.heroku.com
            docker tag nodejs-ipfs-backend-template registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      
      - run:
          name: Download and install Heroku
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Deploy to Heroku
          command: heroku container:release web -a $HEROKU_APP_NAME
